# ++++++++++++++++++++++++++++++++++++++++
# Custom config assets build :

baseurl: ""
url: ""

source: ./src
destination: ./_site_assets_config

custom_assets_config:
  dir: "./assets/config"
  list: 
    - "./common_critic.json"
    - "./common_noncritic.json"
    - "./custom_pages_site.json"
  webpack_base_path: "./webpack/"
  webpack_output_path: "./webpack/output/assets/"


# _layouts/compress.html
compress_html:
  clippings: all
  endings: all
  comments: all # ["<!--", "-->"]

# ! note : coll_dataset with json will be generated too, cause /src/_plugins/jekyll-json-dataset.rb
exclude:
  - _assets
  - _pages
  - _posts
  - index.md
  - 404.html
  - posts.json
  - images
  - assets/dist
  - assets/js
  - assets/scss
  - assets/images
  - assets/fonts
  - favicons
  - feed.xml 

